// AngularProject2026/src/undoable-counter/undoable-counter.component.ts
import { Component, inject } from '@angular/core';
import { formatAction, UndoableCounterStore } from './undoable-counter.store';

@Component({
  selector: 'app-undoable-counter',
  templateUrl: './undoable-counter.component.html',
  styleUrl: './undoable-counter.component.css',
  providers: [UndoableCounterStore],
})
export class UndoableCounterComponent {
  protected readonly store = inject(UndoableCounterStore);

  protected readonly negativeDeltas = [-100, -10, -1] as const;
  protected readonly positiveDeltas = [1, 10, 100] as const;

  protected formatButtonLabel(delta: number): string {
    return `[${formatAction(delta)}]`;
  }
}

<div class="counter-app">
  <h1 class="title">Undoable counter</h1>

  <div class="undo-redo">
    <button type="button" class="btn" [disabled]="!store.canUndo()" (click)="store.undo()">
      Undo
    </button>
    <button type="button" class="btn" [disabled]="!store.canRedo()" (click)="store.redo()">
      Redo
    </button>
  </div>

  <div class="counter-row">
    <div class="delta-group">
      @for (delta of negativeDeltas; track delta) {
        <button type="button" class="btn delta-btn" (click)="store.applyDelta(delta)">
          {{ formatButtonLabel(delta) }}
        </button>
      }
    </div>

    <output class="count-display" aria-live="polite">{{ store.count() }}</output>

    <div class="delta-group">
      @for (delta of positiveDeltas; track delta) {
        <button type="button" class="btn delta-btn" (click)="store.applyDelta(delta)">
          {{ formatButtonLabel(delta) }}
        </button>
      }
    </div>
  </div>

  <section class="history-panel" aria-label="Action history">
    <h2 class="history-title">History</h2>
    <ul class="history-list">
      @for (line of store.historyLines(); track $index) {
        <li>{{ line }}</li>
      }
    </ul>
  </section>
</div>

// apps/react-lab/src/experiments/state-and-data-flow/undoable-counter/UndoableCounter.tsx
import { useUndoableCounter } from './useUndoableCounter';
import './UndoableCounter.css';

const NEGATIVE_DELTAS = [-100, -10, -1] as const;
const POSITIVE_DELTAS = [1, 10, 100] as const;

export default function UndoableCounter() {
  const store = useUndoableCounter();

  return (
    <div className="counter-app">
      <h1 className="title">Undoable counter</h1>

      <div className="undo-redo">
        <button type="button" className="btn" disabled={!store.canUndo} onClick={store.undo}>
          Undo
        </button>
        <button type="button" className="btn" disabled={!store.canRedo} onClick={store.redo}>
          Redo
        </button>
      </div>

      <div className="counter-row">
        <div className="delta-group">
          {NEGATIVE_DELTAS.map((delta) => (
            <button
              key={delta}
              type="button"
              className="btn delta-btn"
              onClick={() => store.applyDelta(delta)}
            >
              {store.formatButtonLabel(delta)}
            </button>
          ))}
        </div>

        <output className="count-display" aria-live="polite">
          {store.count}
        </output>

        <div className="delta-group">
          {POSITIVE_DELTAS.map((delta) => (
            <button
              key={delta}
              type="button"
              className="btn delta-btn"
              onClick={() => store.applyDelta(delta)}
            >
              {store.formatButtonLabel(delta)}
            </button>
          ))}
        </div>
      </div>

      <section className="history-panel" aria-label="Action history">
        <h2 className="history-title">History</h2>
        <ul className="history-list">
          {store.historyLines.map((line, index) => (
            <li key={`${line}-${index}`}>{line}</li>
          ))}
        </ul>
      </section>
    </div>
  );
}
