// apps/angular-lab/src/crypto-converter/crypto-converter.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import {
  CryptoConverterStore,
  CurrencyCode,
  SUPPORTED_CURRENCIES,
} from './crypto-converter.store';

@Component({
  selector: 'app-crypto-converter',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './crypto-converter.component.html',
  styleUrl: './crypto-converter.component.css',
  providers: [CryptoConverterStore],
})
export class CryptoConverterComponent {
  protected readonly store = inject(CryptoConverterStore);
  protected readonly currencies = SUPPORTED_CURRENCIES;

  protected onAmountInput(event: Event): void {
    const value = Number((event.target as HTMLInputElement).value);

    if (!Number.isFinite(value) || value < 0) {
      return;
    }

    this.store.setAmount(value);
  }

  protected onCurrencyChange(event: Event): void {
    const value = (event.target as HTMLSelectElement).value as CurrencyCode;
    this.store.setCurrency(value);
  }

  protected formatWuc(value: number | null): string {
    if (value === null) {
      return '—';
    }

    return value.toFixed(2);
  }

  protected formatChange(value: number | null): string {
    if (value === null) {
      return '';
    }

    const absolute = Math.abs(value).toFixed(2);
    if (value > 0) {
      return `↑ ${absolute}`;
    }

    if (value < 0) {
      return `↓ ${absolute}`;
    }

    return '0.00';
  }

  protected changeDirection(value: number | null): 'up' | 'down' | 'flat' | null {
    if (value === null || value === 0) {
      return value === 0 ? 'flat' : null;
    }

    return value > 0 ? 'up' : 'down';
  }
}

<section class="crypto-converter">
  <h1 class="title">Crypto Converter</h1>
  <p class="subtitle">Convert fiat currency into Wildly Unstable Coin (WUC).</p>

  <div class="controls">
    <input
      type="number"
      class="amount-input"
      min="0"
      step="any"
      aria-label="Amount to convert"
      [value]="store.amount()"
      (input)="onAmountInput($event)"
    />

    <div class="select-wrap">
      <select
        class="currency-select"
        aria-label="Source currency"
        [value]="store.currency()"
        (change)="onCurrencyChange($event)"
      >
        @for (currency of currencies; track currency) {
          <option [value]="currency">{{ currency }}</option>
        }
      </select>
    </div>
  </div>

  <div class="result-row" aria-live="polite">
    @if (store.error(); as errorMessage) {
      <p class="error">{{ errorMessage }}</p>
    } @else {
      <p class="wuc-result">
        <span class="wuc-amount">{{ formatWuc(store.wucAmount()) }} WUC</span>
        @if (changeDirection(store.wucChange()); as direction) {
          <span
            class="wuc-change"
            [class.up]="direction === 'up'"
            [class.down]="direction === 'down'"
            [class.flat]="direction === 'flat'"
          >
            {{ formatChange(store.wucChange()) }}
          </span>
        }
      </p>
    }
  </div>
</section>

// react-demos/src/crypto-converter/CryptoConverter.tsx
import type { ChangeEvent } from 'react';
import { SUPPORTED_CURRENCIES, type CurrencyCode } from './crypto-converter.store';
import { useCryptoConverter } from './useCryptoConverter';
import './CryptoConverter.css';

function formatWuc(value: number | null): string {
  if (value === null) {
    return '—';
  }

  return value.toFixed(2);
}

function formatChange(value: number | null): string {
  if (value === null) {
    return '';
  }

  const absolute = Math.abs(value).toFixed(2);
  if (value > 0) {
    return `↑ ${absolute}`;
  }

  if (value < 0) {
    return `↓ ${absolute}`;
  }

  return '0.00';
}

function changeDirection(value: number | null): 'up' | 'down' | 'flat' | null {
  if (value === null || value === 0) {
    return value === 0 ? 'flat' : null;
  }

  return value > 0 ? 'up' : 'down';
}

export default function CryptoConverter() {
  const store = useCryptoConverter();
  const direction = changeDirection(store.wucChange);

  const onAmountInput = (event: ChangeEvent<HTMLInputElement>) => {
    const value = Number(event.target.value);

    if (!Number.isFinite(value) || value < 0) {
      return;
    }

    store.setAmount(value);
  };

  const onCurrencyChange = (event: ChangeEvent<HTMLSelectElement>) => {
    store.setCurrency(event.target.value as CurrencyCode);
  };

  return (
    <section className="crypto-converter">
      <h1 className="title">Crypto Converter</h1>
      <p className="subtitle">Convert fiat currency into Wildly Unstable Coin (WUC).</p>

      <div className="controls">
        <input
          type="number"
          className="amount-input"
          min={0}
          step="any"
          aria-label="Amount to convert"
          value={store.amount}
          onChange={onAmountInput}
        />

        <div className="select-wrap">
          <select
            className="currency-select"
            aria-label="Source currency"
            value={store.currency}
            onChange={onCurrencyChange}
          >
            {SUPPORTED_CURRENCIES.map((currency) => (
              <option key={currency} value={currency}>
                {currency}
              </option>
            ))}
          </select>
        </div>
      </div>

      <div className="result-row" aria-live="polite">
        {store.error ? (
          <p className="error">{store.error}</p>
        ) : (
          <p className="wuc-result">
            <span className="wuc-amount">{formatWuc(store.wucAmount)} WUC</span>
            {direction !== null && (
              <span className={`wuc-change ${direction}`}>{formatChange(store.wucChange)}</span>
            )}
          </p>
        )}
      </div>
    </section>
  );
}
